# Generated by Django 3.1rc1 on 2020-07-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tablecolumn_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.table'),
        ),
        migrations.AlterField(
            model_name='tablecolumn',
            name='column_type',
            field=models.CharField(choices=[('int', 'int'), ('float', 'float'), ('text', 'text'), ('date', 'date'), ('bool', 'bool'), ('object', 'object'), ('enum', 'enum')], max_length=20),
        ),
    ]
