# Generated by Django 3.1rc1 on 2020-07-30 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200728_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'permissions': (('view', 'View'), ('change', 'View'), ('delete', 'View'))},
        ),
    ]
