# Generated by Django 3.1rc1 on 2020-07-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200730_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
