# Generated by Django 3.1rc1 on 2020-07-30 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_database_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecolumn',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.database'),
        ),
        migrations.AlterUniqueTogether(
            name='tablecolumn',
            unique_together={('table', 'slug')},
        ),
    ]
