# Generated by Django 3.1rc1 on 2020-08-03 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20200730_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='last_edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='last_edit_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_table_edits', to=settings.AUTH_USER_MODEL),
        ),
    ]
