# Generated by Django 3.1rc1 on 2020-08-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200803_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
