# Generated by Django 3.1rc1 on 2020-08-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_table_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
